### PR TITLE
Update payload.js

### PR DESCRIPTION
**Pull request by Aka-but-nice**
ok this is just ridiculous. `(id) => {return document.getElementById(id)};` why are there curly brackets around the arrow function :skull:?

### CODE REVIEW

**Comment by Aka-but-nice** [comment]
??

**Comment by ading2210** [comment]
You submitted something that's completely pointless and you're surprised that I'm denying it?

**Comment by Aka-but-nice** [comment]
my question is, what maniac uses curly brackets for something like `document.getElementById(id)` :skull: but idc

**Comment by ading2210** [comment]
I don't care either.

**Pull request closed without merging**
